Create UDLS page
ksoc-gradsac/ksoc-gradsac.github.io pull request #17
Opened 2023-09-16 23:17 UTC by sohambagchi

2023-09-16 23:40 UTC, jakobottar commented
should the UDLS page be under the "Events" tab?

2023-09-16 23:50 UTC, jakobottar requested changes
The tables are not rendering properly. You need a newline between the headings and the tables. Also, add a table of contents. Just copy/paste this at the top of the doc after the header:

```
{: .no_toc }

## Table of contents
{: .no_toc .text-delta }

1. TOC
{:toc}
```

See `campus_resouces/food.md`.

2023-09-17 22:24 UTC, sohambagchi commented
Line breaks and TOC added

2023-09-18 01:04 UTC, jakobottar approved these changes

2023-09-18 01:05 UTC, merged